INSERT INTO DEMO_USER(USER_CODE,PCODE,USER_ROLE)
  SELECT 'admin', '$2a$10$9S4xNxcObK8zL9k96htl5e8DaeF/nw1tkqKgcL6nhRavXEsAKPdfS', 'ROLE_ADMIN'
  WHERE
  NOT EXISTS (
    SELECT USER_CODE FROM DEMO_USER WHERE USER_CODE = 'admin'
  );